[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Custom 404 page
[build.processing.html]
  pretty_urls = true

# Ensure 404 page is used
[[plugins]]
  package = "@netlify/plugin-nextjs"

  [plugins.inputs]
  # Disable Next.js specific features
  nextjs = false